version: "3"
services:
  bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - DEVELOPER_ID=${DEVELOPER_ID}
      - CLIENT_ID=${CLIENT_ID}
      - ASSISTAND_ID=${ASSISTAND_ID}
